name: ESLint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      with:
        repo-token: ${{ secrets.ESLINT_TOKEN }}
